### ISSUE TITLE
Backpack bug join multiplayer server

### ISSUE THREAD

**Issue by boyandres** [Tiviacz1337/Travelers-Backpack#788] opened 2023-12-22 21:34 UTC
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Forge 1.20.1

1. Describe the bug 

I saw another forum here with the same issue, but I haven't found any solutions like theirs. It turns out that when I enter my server, my backpack doesn't appear, and it shows as equipped when I put on another backpack. I can't interact with it either, and to recover it, I have to kill myself and wait for it to drop. I tried a previous version, but it still happens.

2. Write steps to reproduce the bug

Exit the server and join 

3. What is expected behaviour 

I want the backpack to appear upon entering without any issues because this greatly affects gameplay.

4. Screenshots (If applicable)

![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/80431674/3ff9e94f-27e1-4ce3-9791-ff8332b297b4)
(translation: you already have a backpack)

(Mod list)
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/80431674/a5929705-b884-4377-84dc-f1cf1fa385d4)

**Comment by Tiviacz1337** [comment] 2023-12-24 10:06
does it happen with only travelers backpack installed

**Comment by boyandres** [comment] 2023-12-24 18:03
yes

**Comment by Miah17** [comment] 2023-12-25 01:23
I'm having the same issue as well, worked fine till I logged off for the day. Got back on today the bag disappeared. You cant interact with also. So I thought I lost it so I crafted another, tried to put on and it said "other bag is on already". Like boyamdres said I died then I was able to put on the new bag... There is a work around I tried and seems to work "for now". Take bag off before logging off... BUT If the game crashes or the internet goes down for a min then we'll be at square one again LoL

**Comment by boyandres** [comment] 2023-12-25 03:12
Yes, I've been using the same method as a temporary workaround until I find a solution to the issue. It's really annoying because you have to remember to take off your backpack before leaving, and sometimes you forget. If there's a patch or something like that, it would be great, honestly.

**Comment by Tiviacz1337** [comment] 2023-12-25 20:21
is it possible for one of you or both to check the file i'll send via private message and test if issue still occurs? because im not able to reproduce the issue

**Comment by boyandres** [comment] 2023-12-25 20:42
sure

**Comment by Miah17** [comment] 2023-12-26 04:49
Sure, just to clarify I'm using it in a fabric server. The person that looks over the server gave us the mods to use. I'll ask if I can forward this to him. Others are having issues also... I'm my solo game its fine.

Dec 25, 2023, 1:21 PM by ***@***.***:

**Comment by Tiviacz1337** [comment] 2023-12-27 02:00
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack/files?page=1&pageSize=20
https://modrinth.com/mod/travelersbackpack/versions
should be fixed for forge

**Closed** 2023-12-27 02:10 UTC

**Comment by Miah17** [comment] 2023-12-27 02:12
Okie I'll wait for fabric version... Thanks


Dec 26, 2023, 7:00 PM by ***@***.***:
