### ISSUE TITLE
Fluid Tanks not Working Properly

### ISSUE THREAD

**Issue by MrTailson** [Tiviacz1337/Travelers-Backpack#262] opened 2021-03-01 10:44 UTC
**Describe the bug**
When placing an empty bucket into the slot at the top of a filled tank of any liquid, the liquid does not get taken out and filled in the bucket as it is suppose to. You are only able to put fluids into the tank but can't take any out.

**To Reproduce**
1. Place a bucket of either water or lava into the top slot of a fluid tank to fill it with any amount.
2. Place the empty bucket at the top slot once more and the bucket won't get filled.

**Expected behavior**
When placing an empty bucket at the top slot of one of the fluid tanks, when they are containing any amount of fluid, the bucket should take an amount out from the tanks and fill the bucket.

**Screenshots**

**Required informations (please complete the following information):**
 - TravelersBackpack-1.16.4-5.3.8
 - Forge 1.16.5-36.0.43

**Additional context**

**Comment by Tiviacz1337** [comment] 2021-03-13 12:48
Does it happen every time?

**Comment by MrTailson** [comment] 2021-03-13 17:08
> Does it happen every time?
> I can't reproduce this issue, i've encountered this once, since then everything works fine ;/

Yes, it happens everytime. I'm unsure of anything else that could be affecting it, as all my mods worked fine up until now suddenly.

**Comment by Tiviacz1337** [comment] 2021-03-13 17:24
Hmm do you play on your selfmade modpack?
Do you play on server? 
Have you tried removing fluid from backpack in other form (block or in hand?) 
Have you tried using any other fluid container?

**Comment by MrTailson** [comment] 2021-03-13 17:26
> Hmm do you play on your selfmade modpack?
> Do you play on server?
> Have you tried removing fluid from backpack in other form (block or in hand?)
> Have you tried using any other fluid container?

I play on a Lan world with my friends, who all have the exact same things as me to avoid conflictions. I do not know how to remove liquids from the backpack in any other way.

**Comment by Tiviacz1337** [comment] 2021-03-13 17:34
I mean you can place backpack on the ground, then open inventory and check if it works

**Comment by MrTailson** [comment] 2021-03-13 17:36
> I mean you can place backpack on the ground, then open inventory and check if it works

Oh right, I completely forgot that. I will get back to you after I check that.

**Comment by Tiviacz1337** [comment] 2021-03-14 11:58
Did you check it?

**Comment by MrTailson** [comment] 2021-03-14 18:31
> Did you check it?

Yes, I checked it. That method does not work either. I also tried opening the backpack while it was in my hand, and nothing worked.

**Comment by Tiviacz1337** [comment] 2021-03-14 19:18
could you give me your modpack?

**Comment by MrTailson** [comment] 2021-03-14 19:19
I don't use a mod pack, I just downloaded a bunch. How would I go about sharing them?

**Comment by Tiviacz1337** [comment] 2021-03-14 19:49
How many mods do you use?

**Comment by MrTailson** [comment] 2021-03-14 19:50
> How many mods do you use?

Oh boy... Uh, more than 60 I think?

**Comment by t4ggno** [comment] 2021-03-15 01:36
Hello, 
I have the same problem. I can fill the tank but im unable to pull out the water. Couldn't try the hose, because I currently missing a green dye :/

![image](https://user-images.githubusercontent.com/14984216/111092728-25df0380-8537-11eb-8b3c-86862366ca62.png)

Here is my list of mods. Probably it will help you to find out, what's the problem.

Server + Client:
![image](https://user-images.githubusercontent.com/14984216/111092385-3e025300-8536-11eb-8323-4840d4cb0e10.png)

Client only:
![image](https://user-images.githubusercontent.com/14984216/111092609-cda80180-8536-11eb-9a45-5a0888c7b9a0.png)

**Comment by zS1m** [comment] 2021-03-15 01:49
I have the problem as well, I can't take out my liquid wheather the backpack is on the ground or not.
Here is my list of mods.

![list](https://user-images.githubusercontent.com/41533924/111093304-8724c800-8573-11eb-89aa-9af20fb74496.png)

**Comment by Tiviacz1337** [comment] 2021-03-15 09:27
Thank you guys I'll try to figure it out

**Comment by lone-wolf-akela** [comment] 2021-03-15 09:49
> Thank you guys I'll try to figure it out

I can confirm this bug happens with only Travelers Backpack and no other mod installed.
Also, this bug happens with Forge 36.0.58, but not with Forge 36.0.0

**Comment by Tiviacz1337** [comment] 2021-03-17 08:20
I've just checked if problem persists with 36.0.58 in my workspace and everything is working fine ;8

**Comment by Tiviacz1337** [comment] 2021-03-17 09:27
Okay it seems like It's already fixed in my workspace, 5.3.8 does not work, It'll work in the next update

**Comment by Tiviacz1337** [comment] 2021-03-18 08:01
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3243518

**Closed by Tiviacz1337** 2021-03-18 08:01 UTC
Labels: Fixed in dev, bug, help wanted
