### ISSUE TITLE
Items disappear after using shift + left click

### ISSUE THREAD

**Issue by Stevendotcom** [Tiviacz1337/Travelers-Backpack#846] opened 2024-03-16 20:00 UTC
0. Fabric 1.20.1 with TB 9.1.9

1. Describe the bug 
When using shift + left click with various items to move them from inventory to the backpack, and then closing the backpack and opening again, the items that were stored are now gone

2. Write steps to reproduce the bug

- Open backpack
- Use left click + shift
- close Backpack
- Open Again
- items gone 

3. What is expected behaviour 

For the tiems to still be there

**Comment by Stevendotcom** [comment] 2024-03-16 20:01
After testing it, only the first items is stored

**Comment by Tiviacz1337** [comment] 2024-03-17 12:07
Do you play on server?

**Comment by scurius** [comment] 2024-03-17 19:11
I had the same issue, it seems to be caused by the last Trinkets mod update.

**Comment by Stevendotcom** [comment] 2024-03-18 11:43
Shoot, then the fix might be there and not here
Sad

Also not playing online, just single player

**Comment by Tiviacz1337** [comment] 2024-03-18 12:23
this issue will be fixed in upcoming update for fabric

**Comment by Tiviacz1337** [comment] 2024-03-18 22:46
I can't reproduce the issue

**Comment by Tiviacz1337** [comment] 2024-03-18 22:48
All my items are saved correctly, what fabric version do you use

**Comment by NolanHewitt** [comment] 2024-03-20 06:25
Can confirm this issue on my end. Using quilt loader 0.24

**Comment by Tiviacz1337** [comment] 2024-03-24 12:39
https://modrinth.com/mod/travelersbackpack/versions
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all?page=1&pageSize=20
Fixed for Fabric

**Closed by Tiviacz1337** 2024-03-24 12:39 UTC
Labels: fixed in dev, Fabric

**Comment by App4ri** [comment] 2024-03-26 22:07
I just lost all my items to this same bug.
I joined my world and opened it to find that the crafting grid had changed and all my items deleted.
I really enjoyed that world, but since all my items are gone there is no reason for me to play it anymore.
