### ISSUE TITLE
Water in backback causing hud glitch

### ISSUE THREAD

**Issue by ayoitsmaggs** [Tiviacz1337/Travelers-Backpack#902] opened 2024-05-08 23:34 UTC
Using 1.20.4 Fabric with lots of mods but the backpack is the source of the issue it seems
When putting water in the backpack, any hotbar items that have an enchanted glint get a weird blue filter. When in any storage container the GUI looks fine but the Hotbar stays blue. Removing the backpack while it has water fixes the issue so it only seems to happen when the backpack is equipped with water in the tank. Lava did not affect anything

![Screenshot 2024-05-08 190201](https://github.com/Tiviacz1337/Travelers-Backpack/assets/98441829/fe18aeab-1610-4e74-9805-d4bbcba6de86)

Another issue is the black cube on the bottom right. I removed all shaders and texture packs and still could reproduce the same issue the same issue. 

Was able to change the issue to having all blacked-out hotbars when no water and the same blue effect with water by deleting the travelers_backpack_overlay.png after looking through the mod with Winrar so the issue may stem from there

https://github.com/Tiviacz1337/Travelers-Backpack/assets/98441829/36fddbcc-5b81-458f-8b1a-f50f03991637

**Comment by Tiviacz1337** [comment] 2024-05-10 14:08
What version do you use?

**Comment by ayoitsmaggs** [comment] 2024-05-10 14:18
I’m using 1.20.4 and i believe it was on fabric 0.15.11 but may have been at ten. i can check when i am out of school.

**Comment by Tiviacz1337** [comment] 2024-05-10 17:13
mod version

**Comment by ayoitsmaggs** [comment] 2024-05-10 19:10
9.4.0

**Comment by Tiviacz1337** [comment] 2024-05-18 00:35
I'm using the latest version and can't reproduce the issue, I'm going to release new version soon for fabric marked as stable release if you don't want to update to beta

**Comment by 0xK3vin** [comment] 2024-05-19 19:06
+1 same thing is happening to me only when backpack has water.

**Comment by Tiviacz1337** [comment] 2024-05-19 19:39
> +1 same thing is happening to me only when backpack has water.

May I know what version do you use?

**Comment by 0xK3vin** [comment] 2024-05-19 23:39
fabric-1.20.1-9.1.12

**Comment by Tiviacz1337** [comment] 2024-05-20 13:55
Do you play on any modpack so I can check it myself?

**Comment by Tiviacz1337** [comment] 2024-05-20 15:01
Changed some code that is responsible for rendering hud overlay, when I release an update I'll link it here, hopefully it fixes the issue, because I can't reproduce it

**Comment by Hyperbuss** [comment] 2024-05-20 19:50
I have the same issue, 1.20.1 Fabric

**Comment by Tiviacz1337** [comment] 2024-05-20 20:03
Could you check if issue occurs with travelers backpack installed only

**Comment by Hyperbuss** [comment] 2024-05-20 20:20
it's only when I have water in my backpack's tank. The water tank is just kinda strange in general, using the hose isn't updating the Hud icon levels

**Comment by Tiviacz1337** [comment] 2024-05-23 13:48
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all
Check if issue still occurs

**Comment by Tiviacz1337** [comment] 2024-05-25 23:03
Any update?

**Comment by albdag** [comment] 2024-06-01 11:00
Had the same issue (fabric 1.20.4). Now I have installed the last version (9.4.4) and it's solved! Thanks.

**Comment by Tiviacz1337** [comment] 2024-06-01 11:01
Thanks for confirmation, closing

**Closed as completed** 2024-06-01 11:01 UTC
Labels: bug, fabric
