### ISSUE TITLE
backpacks & items in backpack disappearing

### ISSUE THREAD

**Issue by sealestiale** [Tiviacz1337/Travelers-Backpack#996] opened 2024-08-16 00:26 UTC
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

fabric 1.21-10.0.6

1. Describe the bug 

backpacks and items inside backpacks are randomly disappearing. i could be organizing some things in one second and close it, then when i open it again, everything is gone. for some reason. my water buckets were still there though. another situation happened that had one of my backpacks completely disappear.

2. Write steps to reproduce the bug

i have no idea how this is happening.

3. What is expected behaviour 

i would like my things to not disappear

4. Screenshots (If applicable)
![2024-08-15_19 23 37](https://github.com/user-attachments/assets/0d14adc6-a210-465a-86f3-7069656391f8)

![2024-08-15_19 23 29](https://github.com/user-attachments/assets/d48f9f52-fe3b-4282-9cd9-2513fbd37c10)

(the first file is what is in my hay backpack, as an example  for the kind of things that was in the backpack next to it. the second file is the now completely empty backpack that was full of seeds and such.)

**Comment by Tiviacz1337** [comment] 2024-08-17 14:59
Need steps how to reproduce the issue. Do you use accessories integration?

**Comment by sealestiale** [comment] 2024-08-18 00:01
i do have accessories integration. i'm not sure how it keeps disappearing, so i dont know how to reproduce it

**Comment by ARoyalPain** [comment] 2024-09-05 00:56
The way ive been able to recreate the problem is just by fully closing your game and rejoining soon after adding items to your backpack. I believe ive figured out the issue. Its one of two things, Either the Accessories mod version your are using is the problem because as of today they fixed a problem with trinket inventory syncing issues, or the other theory is the current version of Travelers Backpack has an inventory Syncing issue that needs to be adressed.

**Comment by Tiviacz1337** [comment] 2024-09-25 09:16
This issue should be fixed on travelersbackpack 10.1.2, I've changed saving method for accessories/trinkets integration

**Closed as completed by Tiviacz1337** 2024-09-25 09:16 UTC
Labels: fixed in dev
