### ISSUE TITLE
Travelers Bag crashes with crafting upgrade

### ISSUE THREAD

**Issue by xaltraUnderscore** [Tiviacz1337/Travelers-Backpack#1041] opened 2024-10-06 23:51 UTC
0. Fabric 9.1.17

1. After installing a crafting upgrade into a Diamond Backpack (only bag I have used) it crashes

2. Make diamond backpack, upgrade to diamond tier, add crafting upgrade, and open crafting menu.

3. Opens crafting menu

4. Screenshots Unapplicable

**Comment by Tiviacz1337** [comment] 2024-10-07 00:27
I can't reproduce this issue, you have to share crash log

**Comment by xaltraUnderscore** [comment] 2024-10-07 00:49
[crash-2024-10-06_18.28.16-client.txt](https://github.com/user-attachments/files/17271472/crash-2024-10-06_18.28.16-client.txt)

**Comment by Tiviacz1337** [comment] 2024-10-07 13:19
This must be some mod incompatibility issue, I've checked it and still can't reproduce. Do you play on your custom modpack or some modpack from curseforge/modrinth?

**Comment by xaltraUnderscore** [comment] 2024-10-07 13:32
BigChadGuys+ w/Cobblemon

**Comment by Tiviacz1337** [comment] 2024-10-07 13:42
![image](https://github.com/user-attachments/assets/702774b2-eb25-4b9e-8a11-a447ba94922a)
I can use it just fine, Do you play on server?

**Comment by Tiviacz1337** [comment] 2024-10-07 13:57
Okay I had to add crafting tweaks and now I can reproduce the issue, I'll work on a fix

**Comment by xaltraUnderscore** [comment] 2024-10-07 14:06
Sorry for forgetting the mod i added, it didnt cross my mind.

**Comment by Tiviacz1337** [comment] 2024-10-07 14:27
Fix will be released this week

**Comment by Tiviacz1337** [comment] 2024-10-14 22:51
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/5812761
Fixed

**Closed as completed by Tiviacz1337** 2024-10-14 22:51 UTC
Labels: fixed in dev, fabric
