### ISSUE TITLE
[1.20.1 Forge] Crash with EMI from lava.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by templeofshadow** [Tiviacz1337/Travelers-Backpack#945] opened 2024-07-04 09:12 UTC
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Forge 1.20.1, mod version 1.20.1-9.1.14

1. Describe the bug 

Crash upon opening backpack, almost immediately after placing backpack on ground.

I didn't really do anything weird, but after the game froze I noticed that the backpack inventory UI overlapped with the player inventory.

Here is my crash log: 
[crash-2024-07-04_03.54.49-client.txt](https://github.com/user-attachments/files/16096098/crash-2024-07-04_03.54.49-client.txt)

2. Write steps to reproduce the bug

I have no idea if this is reproducible. I didn't do anything in particular that I think would have caused any issues.

With that being said, this is what I did:
-Place a diamond-tier normal backpack on the ground
-Open it almost immediately
-Game freezes and then crashes

3. What is expected behaviour 

Not crashing, with the inventory of the backpack opening normally.

4. Screenshots (If applicable)

I wasn't fast enough to snap a screenshot of the weird UI, unfortunately. 

--

As I mentioned, I have no idea if this is reproducible because I didn't do anything in particular that would've caused any issues. Please let me know if you need any more info.

**Comment by Tiviacz1337** [comment] 2024-07-11 12:39
Can't reproduce this issue, probably some bug with wrong backpack data or something

**Comment by Tiviacz1337** [comment] 2024-07-11 12:40
Do you know how to reproduce?

**Comment by templeofshadow** [comment] 2024-07-11 13:42
I honestly have no idea. This hasn't happened to me again over the last few days, and I didn't know how to go about testing in order to find the bug, since I didn't do anything weird. 

I think it's probably some rare UI bug, maybe somewhere in the backpack UI placement code? I'm making this guess based on the UI being misplaced and overlapping after the game froze during the crash. 

Since I don't know anything about how this happened, I basically just decided to throw this issue up to both see if this is a known bug and to see if this has happened to anyone else. 

While I'm here, I'll drop the log for this just in case it's useful:
[2024-07-04-1.log](https://github.com/user-attachments/files/16177927/2024-07-04-1.log)

I also still have the debug log for this crash, but it's >25mb so github won't let me attach it to this comment. Let me know if you want this too and I'll find a way to get it to you.

**Comment by Tiviacz1337** [comment] 2024-07-12 11:49
If it happens next time make sure to remember what you do to reproduce the issue and reopen. Probably some rare bug with data initialization. Closing for now

**Closed as completed by Tiviacz1337** 2024-07-12 11:49 UTC
Labels: compat
